<?php
session_start();
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="css/style.css">
        <script src="js/hero.js" async></script>
        <script src="js/choose-a-scooter.js" async></script>
        <title>Piaggio Scooters - Made in Italy</title>
    </head>
    <body>
        <?php
        include "inc/header.inc.php";
        ?>
        <main>
            <section id="mission">
                <div>
                    <h1>Piaggio<br><span>Scooters</span></h1>
                    <q>Real life stories of ordinary daily journeys that become extraordinary</q>
                    <figure class="hero-box">
                        <img id="hero-img" src="" alt="">
                        <div class="left-arrow"></div>
                        <div class="right-arrow"></div>
                        <div class="radio-box">
                            <div id="img1" class="radio-active"></div>
                            <div id="img2"></div>
                            <div id="img3"></div>
                            <div id="img4"></div>
                            <div id="img5"></div>
                        </div>
                        <button id="play">&#9654;</button>
                        <button id="pause">&#10073;&#10073;</button>
                    </figure>
                    <p class="intro-text">Behind every Piaggio vehicle is the story of a great adventure that started way back in Sestri Ponente, Genova, in 1884 when young Rinaldo Piaggio took over his father’s business and converted it into a marine fit out company. Little did he know that within a few years Piaggio & Co would go on to conquer the skies, the roads and the hearts of all of Italy.</p>
                </div>
                
            </section>
            <section id="models">

                <h2> Our Models</h2>

                <section id="model-categories">
                    <button id="cat-all">All</button>
                    <button id="cat-mp3">MP3</button>
                    <button id="cat-liberty">Liberty</button>
                    <button id="cat-bv">BV</button>
                    <button id="cat-piaggio-1">Piaggio 1</button>
                </section>
                
                <section id="model-types">                
                    <!-- Generated by JS -->
                </section>
            </section>
            <section id="team">
                <h2>Our Team</h2>
                <div class="chef">
                    <figure>
                        <img src="images/person_3.webp" alt="">
                        <figcaption>Angelo Balducci<br>CEO</figcaption>
                    </figure>
                    <figure>
                        <img src="images/person_1.jpeg" alt="">
                        <figcaption>Bruno Moratti<br>Chief Technology Officer</figcaption>
                    </figure>
                    <figure>
                        <img src="images/person_2.webp" alt="">
                        <figcaption>Sofia Lunati<br>Chief Design Officer</figcaption>
                    </figure>         
                </div>
                <p>At our Italian scooter company, the team is deeply committed to creating high-quality, stylish, and functional scooters for their customers. From the designers to the engineers to the factory workers, everyone is dedicated to producing the best possible product.
                </p>
                <p>   
                Our team understands that our scooters are not just a means of transportation but also a reflection of the customer's personality and lifestyle. Therefore, we pay close attention to every detail, from the design and materials to the manufacturing process and final product.
                </p>
                <p>
                Our commitment is reflected in the quality of our scooters, which are known for their durability, performance, and style. Customers can trust that when they purchase a scooter from us, they are investing in a product that has been created with care and passion by a team that truly believes in its value.
                </p>
            </section>
            <section id="popup">
                <button id="close-popup"> x </button>
            </section>
        </main>
        <?php
        include "inc/footer.inc.php";
        ?>
    </body>
</html>